x-common-network: &common-network
  networks:
    - microservices-net

x-zipkin-env: &zipkin-env
  environment:
    - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411

x-java-depends: &java-depends
  depends_on:
    configserver:
      condition: service_healthy
    discovery:
      condition: service_started
    zipkin:
      condition: service_started

services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports: ["9411:9411"]
    <<: *common-network

  configserver:
    container_name: configserver
    image: afra2112/configserver-service:1.0
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports: ["8888:8888"]
    <<: *common-network

  discovery:
    container_name: discovery
    image: afra2112/discovery-service:1.0
    ports: ["8761:8761"]
    depends_on:
      configserver:
        condition: service_healthy
    <<: *common-network

  product:
    container_name: product
    image: afra2112/product-service:1.0
    ports: ["8200:8200"]
    <<: [*common-network, *zipkin-env, *java-depends]

  customer:
    container_name: customer
    image: afra2112/customer-service:1.0
    ports: ["8100:8100"]
    <<: [*common-network, *zipkin-env, *java-depends]

  order:
    container_name: order
    image: afra2112/order-service:1.0
    ports: ["8300:8300"]
    <<: [*common-network, *zipkin-env, *java-depends]

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports: ["3306:3306"]
    <<: *common-network

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5607
      - POSTGRES_DB=orders
    ports: ["5431:5432"]
    <<: *common-network

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mongo: